### ISSUE TITLE
comparing exact solution and transformed solution

### ISSUE THREAD

**Issue by TiKeil** [gridlod-community/gridlod-on-perturbations#2]
In 1d, we only visually see that the variable transformation works. In 2d it does not even seem to work. 

In general, we need a sufficient comparison of u_pert and u_transformed. Right now, we have a very bad convergence and it's not clear whether this comes from the method, the test case or the error comparison.

Note:
In plateau_1d.py, we have a good visual convergence but a bad error convergence (in energy norm)
In plateau_2d_on_one_axis.py, we have no visual convergence!  <-- This is probably the most important thing to work on right now.

**Comment by fredrikhellman** [comment]
I have started looking into this. I have not found any error yet, but I have not yet gone through everything. I am writing a list of things to add or change. It is very good for me to see how your code starts to look like, because that makes me see what kind of additional functionality we need. I will try to work on the train in the mornings and evenings the coming week with the code to see if I can find what it is.

**Comment by fredrikhellman** [comment]
The work_on_mappings branch seems to solve these issues.

**Comment by TiKeil** [comment]
Thats correct, I will close this now.
